"""Semantic problem equivalence over community questions.

Mission 1.24, from the design in `semantic-problem-equivalence-v1.md`.

The package is deliberately narrow: it generates candidates, holds a versioned
rubric, builds a prompt whose regions stay separated, classifies through the LLM
Gateway, and evaluates the result against human labels. It persists nothing,
opens no socket, and names no provider.
"""

from .batch import (
    BATCH_SELECTION_VERSION,
    FAMILY_BATCH_SELECTION_VERSION,
    FAMILY_HOLDOUT_EXCLUSIONS,
    FAMILY_HOLDOUT_FRACTION,
    FAMILY_SPLIT_SEED,
    ReviewBatch,
    ReviewItem,
    assign_family_split,
    select_family_review_batch,
    select_review_batch,
)
from .candidates import (
    CANDIDATE_GENERATOR_VERSION,
    CandidatePair,
    CandidateSet,
    QuestionObservation,
    generate_candidates,
)
from .classifier import (
    CLASSIFIER_TASK,
    SEMANTIC_TIER,
    ClassificationRefusedError,
    EquivalenceClassification,
    ExternalInferenceAuthorization,
    classify_pair,
)
from .evaluation import (
    ACCEPTANCE_CRITERIA,
    FAMILY_V1_ACCEPTANCE,
    HOLDOUT_EXCLUSIONS,
    SPLIT_SEED,
    V1_ACCEPTANCE,
    V2_ACCEPTANCE,
    AcceptanceCriterion,
    EvaluationResult,
    LabelSet,
    ReferenceDecision,
    ReferenceLabel,
    ReferenceOrigin,
    Split,
    assign_split,
    evaluate,
)
from .family_candidates import (
    FAMILY_CANDIDATE_GENERATOR_VERSION,
    generate_family_candidates,
    tag_rarity,
)
from .family_classifier import (
    FAMILY_CLASSIFIER_TASK,
    FamilyClassification,
    classify_family_pair,
)
from .family_prompt import (
    FAMILY_OUTPUT_SCHEMA,
    FAMILY_PROMPT,
    FAMILY_PROMPT_ID,
    FAMILY_PROMPT_VERSION,
    render_family_prompt,
)
from .family_rubric import (
    FAMILY_GRANULARITY,
    FAMILY_INSUFFICIENT_ALONE,
    FAMILY_RELATION,
    FAMILY_RUBRIC_TEXT,
    FAMILY_RUBRIC_VERSION,
    FAMILY_WORKED_EXAMPLES,
    FamilyDecision,
    FamilyReasonCode,
    FamilyWorkedExample,
)
from .prompt import (
    EQUIVALENCE_PROMPT,
    OUTPUT_SCHEMA,
    PROMPT_ID,
    PROMPT_VERSION,
    QuestionForPrompt,
    render_equivalence_prompt,
)
from .relations import FORBIDDEN_IMPLICATIONS, EquivalenceRelation
from .rubric import (
    GRANULARITY,
    INSUFFICIENT_ALONE,
    RUBRIC_TEXT,
    RUBRIC_VERSION,
    WORKED_EXAMPLES,
    EquivalenceDecision,
    ReasonCode,
    WorkedExample,
)

__all__ = [
    "render_family_prompt",
    "FAMILY_PROMPT_VERSION",
    "FAMILY_PROMPT_ID",
    "FAMILY_PROMPT",
    "FAMILY_OUTPUT_SCHEMA",
    "classify_family_pair",
    "FamilyClassification",
    "FAMILY_CLASSIFIER_TASK",
    "select_family_review_batch",
    "assign_family_split",
    "FAMILY_SPLIT_SEED",
    "FAMILY_HOLDOUT_FRACTION",
    "FAMILY_HOLDOUT_EXCLUSIONS",
    "FAMILY_BATCH_SELECTION_VERSION",
    "tag_rarity",
    "generate_family_candidates",
    "FamilyWorkedExample",
    "FamilyReasonCode",
    "FamilyDecision",
    "EquivalenceRelation",
    "FORBIDDEN_IMPLICATIONS",
    "FAMILY_WORKED_EXAMPLES",
    "FAMILY_V1_ACCEPTANCE",
    "FAMILY_RUBRIC_VERSION",
    "FAMILY_RUBRIC_TEXT",
    "FAMILY_RELATION",
    "FAMILY_INSUFFICIENT_ALONE",
    "FAMILY_GRANULARITY",
    "FAMILY_CANDIDATE_GENERATOR_VERSION",
    "BATCH_SELECTION_VERSION",
    "CANDIDATE_GENERATOR_VERSION",
    "CLASSIFIER_TASK",
    "EQUIVALENCE_PROMPT",
    "GRANULARITY",
    "HOLDOUT_EXCLUSIONS",
    "INSUFFICIENT_ALONE",
    "OUTPUT_SCHEMA",
    "PROMPT_ID",
    "PROMPT_VERSION",
    "RUBRIC_TEXT",
    "RUBRIC_VERSION",
    "SEMANTIC_TIER",
    "SPLIT_SEED",
    "ACCEPTANCE_CRITERIA",
    "V1_ACCEPTANCE",
    "V2_ACCEPTANCE",
    "WORKED_EXAMPLES",
    "AcceptanceCriterion",
    "CandidatePair",
    "CandidateSet",
    "ClassificationRefusedError",
    "EquivalenceClassification",
    "EquivalenceDecision",
    "EvaluationResult",
    "ExternalInferenceAuthorization",
    "ReferenceDecision",
    "ReferenceLabel",
    "ReferenceOrigin",
    "LabelSet",
    "QuestionForPrompt",
    "QuestionObservation",
    "ReasonCode",
    "ReviewBatch",
    "ReviewItem",
    "Split",
    "WorkedExample",
    "assign_split",
    "classify_pair",
    "evaluate",
    "generate_candidates",
    "render_equivalence_prompt",
    "select_review_batch",
]
