"""Startup Research OS shared domain contracts.

Stdlib only, by design (ADR-009): every service and every tool must be able to
import the domain vocabulary without pulling a dependency tree. Services adapt
these types to Pydantic at their HTTP boundary (ADR-003); the vocabulary itself
stays dependency-free.

The generated vocabulary lives in ``sros_contracts.generated.domain`` and is
derived from ``packages/contracts/schema/domain.v1.json``. Do not edit it.
"""

from __future__ import annotations

from .errors import ContractError
from .generated.domain import (
    CONTRACT_VERSION,
    ONTOLOGY_VERSION,
    REGISTRY_NAMES,
    RESEARCH_CONTEXT_SCHEMA_VERSION,
    AcquisitionErrorCode,
    AggregationProfileStatus,
    AttributionElement,
    ClaimEvidenceRefusalReason,
    ClaimInterpretationKind,
    ClaimLifecycle,
    ClaimOrigin,
    ClaimTemporality,
    ClaimType,
    ConditionVerification,
    ConditionVerificationResult,
    DemandSignalFamily,
    EvidenceAggregationStatus,
    EvidenceDirection,
    EvidenceIndependenceState,
    EvidenceObservationCategory,
    LlmTier,
    MarketScopeType,
    NormalizationErrorCode,
    NormalizationQualityReason,
    NormalizedGeographyKind,
    NormalizedLanguageMapping,
    NormalizedPeriodType,
    NormalizedRecordQuality,
    NormalizedTimezoneState,
    NormalizedUnitState,
    NormalizedValueState,
    ObservationKind,
    PersonalDataRisk,
    PolicyAssessment,
    PolicyEvidenceType,
    RegistryStatus,
    ResearchSessionStatus,
    ResourceContentOrigin,
    RightsBasis,
    ScoreFamily,
    SignalDerivationKind,
    SignalDirection,
    SignalInputRole,
    SignalMagnitudeKind,
    SignalMagnitudeUnitState,
    SignalQuantityFamily,
    SignalRefusalReason,
    SignalRequiredFact,
    SignalTemporalBasis,
    SourceAccessMethod,
    SourceAcquisitionCost,
    SourceApprovalState,
    SourceLifecycle,
)
from .ids import (
    ClaimId,
    EvidenceId,
    OpportunityId,
    ResearchProjectId,
    ResearchSessionId,
    SignalId,
    SourceId,
    UserId,
    WorkspaceId,
)
from .market_scope import MarketScope
from .numeric import (
    confidence,
    confidence_to_percent,
    evidence_level,
    independence,
    probability,
    reliability,
    score,
)
from .registry import RegistryEntry, RegistryRef
from .research_context import BudgetConstraints, ResearchContext

__all__ = [
    "CONTRACT_VERSION",
    "ONTOLOGY_VERSION",
    "RESEARCH_CONTEXT_SCHEMA_VERSION",
    "REGISTRY_NAMES",
    "ContractError",
    "ClaimType",
    "DemandSignalFamily",
    "LlmTier",
    "MarketScopeType",
    "RegistryStatus",
    "ResearchSessionStatus",
    "ScoreFamily",
    "SourceApprovalState",
    "SourceAccessMethod",
    "SourceLifecycle",
    "SourceAcquisitionCost",
    "PolicyAssessment",
    "PolicyEvidenceType",
    "PersonalDataRisk",
    "EvidenceDirection",
    "EvidenceIndependenceState",
    "EvidenceObservationCategory",
    "ClaimTemporality",
    "ClaimOrigin",
    "ClaimLifecycle",
    "ClaimInterpretationKind",
    "ClaimEvidenceRefusalReason",
    "ObservationKind",
    "ConditionVerification",
    "AcquisitionErrorCode",
    "ConditionVerificationResult",
    "AttributionElement",
    "ResourceContentOrigin",
    "RightsBasis",
    "NormalizedRecordQuality",
    "NormalizationQualityReason",
    "NormalizationErrorCode",
    "NormalizedPeriodType",
    "NormalizedGeographyKind",
    "NormalizedLanguageMapping",
    "NormalizedTimezoneState",
    "NormalizedValueState",
    "NormalizedUnitState",
    "SignalQuantityFamily",
    "SignalDirection",
    "SignalMagnitudeKind",
    "SignalMagnitudeUnitState",
    "SignalTemporalBasis",
    "SignalRequiredFact",
    "SignalDerivationKind",
    "SignalInputRole",
    "SignalRefusalReason",
    "AggregationProfileStatus",
    "EvidenceAggregationStatus",
    "UserId",
    "WorkspaceId",
    "ResearchProjectId",
    "ResearchSessionId",
    "OpportunityId",
    "ClaimId",
    "EvidenceId",
    "SignalId",
    "SourceId",
    "MarketScope",
    "RegistryRef",
    "RegistryEntry",
    "ResearchContext",
    "BudgetConstraints",
    "confidence",
    "confidence_to_percent",
    "probability",
    "reliability",
    "independence",
    "score",
    "evidence_level",
]
