"""Mission 1.85.2 (roadmap N05). Predecessor replay for the independence-level repair.

`--record-predecessor` runs ONCE, under algorithm 1.0.0, before `levels.py` changes. It writes
`docs/data/evidence-aggregation-independence-level-predecessor-v1.json`: the canonical aggregation output
of every differential case, and of every real claim in the deployment when `DATABASE_URL` is set
(read-only). It refuses to run under any other algorithm version and refuses to overwrite the record,
because a predecessor baseline regenerated by the successor is not a baseline.

`--compare` re-runs the same inputs under the current code and checks the repair's contract against that
record: every mass, count, warning, explanation and score identical; no level higher; only the
Repeated Signal and Strong Multi-Source reasons may differ. Real rows are compared when `DATABASE_URL` is
set. Exit 1 on any violation.

Nothing here writes to the database, calls a model or reaches the network.

    uv run python infrastructure/scripts/evidence_independence_level_replay.py --record-predecessor
    uv run python infrastructure/scripts/evidence_independence_level_replay.py --compare
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
import pathlib
import sys
from datetime import UTC, datetime
from typing import Any

ROOT = pathlib.Path(__file__).resolve().parents[2]
SCRIPTS = ROOT / "infrastructure" / "scripts"
RECORD = ROOT / "docs" / "data" / "evidence-aggregation-independence-level-predecessor-v1.json"
CASES_FILE = (
    ROOT / "packages" / "evidence-aggregation" / "python" / "tests" / "independence_level_cases.py"
)
PREDECESSOR_ALGORITHM = "1.0.0"

#: Fields of a result the repair is allowed to move. Everything else must be byte-identical.
LEVEL_FIELDS = ("evidence_level", "label", "reasons", "blocked_reasons")
#: The only reasons the repair may change: the two thresholds based on established independence.
THRESHOLD_MARKERS = ("Repeated Signal", "Strong Multi-Source", "independent groups across")


def _module(name: str, path: pathlib.Path) -> Any:
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise SystemExit(f"FAIL     cannot load {path.name}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _digest(payload: dict[str, Any]) -> str:
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()


def case_results() -> dict[str, Any]:
    cases = _module("independence_level_cases_for_replay", CASES_FILE)
    out: dict[str, Any] = {}
    for case_id, items in cases.CASES.items():
        canonical = {cases.run(order).canonical_json() for order in cases.permutations(items)}
        if len(canonical) != 1:
            raise SystemExit(f"FAIL     {case_id} is not order-invariant")
        out[case_id] = json.loads(canonical.pop())
    return out


def real_row_results(url: str) -> dict[str, Any]:
    import psycopg
    from sros_contracts import (
        ClaimTemporality,
        ClaimType,
        ReliabilityAssessmentOrigin,
        ReliabilityBasisType,
    )
    from sros_evidence_aggregation import REFERENCE_PROFILE_V1, aggregate, evidence_item_from_row
    from sros_evidence_reliability import (
        ReliabilityAssessment,
        ReliabilityBasis,
        ReliabilityScope,
        resolve_reliability,
    )

    sql = _module(
        "falsifiable_gap_sql_for_replay", SCRIPTS / "measure_falsifiable_apparatus_gap_baseline.py"
    )
    with psycopg.connect(url) as conn, conn.cursor() as cur:
        cur.execute("SET TRANSACTION READ ONLY")
        cur.execute(sql.ROWS)
        cols = [d.name for d in cur.description]
        rows = [dict(zip(cols, r, strict=True)) for r in cur.fetchall()]
        cur.execute(sql.ASSESSMENTS)
        acols = [d.name for d in cur.description]
        raw_assessments = [dict(zip(acols, r, strict=True)) for r in cur.fetchall()]
        cur.execute(sql.BASIS)
        bcols = [d.name for d in cur.description]
        basis: dict[str, list[dict[str, Any]]] = {}
        for record in cur.fetchall():
            row = dict(zip(bcols, record, strict=True))
            basis.setdefault(str(row["assessment_id"]), []).append(row)
        cur.execute("SELECT independence_state, count(*) FROM scoring.evidence GROUP BY 1")
        states = {k: int(v) for k, v in cur.fetchall()}
        conn.rollback()

    live = [
        ReliabilityAssessment(
            id=str(a["id"]),
            scope=ReliabilityScope(
                source_id=a["source_id"],
                resource_id=a["resource_id"],
                record_kind_id=a["record_kind_id"],
                claim_type=ClaimType(a["claim_type"]),
                proposition_kind=a["proposition_kind"],
            ),
            version=int(a["version"]),
            reliability=float(a["reliability"]),
            origin=ReliabilityAssessmentOrigin(a["origin"]),
            rationale="(not reproduced here)",
            stated_limitation=a["stated_limitation"],
            reviewed_by=a["reviewed_by"],
            reviewed_at=a["reviewed_at"],
            basis=tuple(
                ReliabilityBasis(
                    basis_type=ReliabilityBasisType(b["basis_type"]),
                    document_title=b["document_title"],
                    summarized_finding=b["summarized_finding"],
                    document_url=b["document_url"],
                    section_reference=b["section_reference"],
                    retrieved_at=b["retrieved_at"],
                )
                for b in basis.get(str(a["id"]), ())
            ),
            calibration_dataset_ref=None,
            review_rubric_id=a["review_rubric_id"],
            review_rubric_version=a["review_rubric_version"],
        )
        for a in raw_assessments
    ]
    by_claim: dict[str, list[dict[str, Any]]] = {}
    for row in rows:
        facts = row["proposition_facts"] or {}
        scope = ReliabilityScope(
            source_id=row["source_id"],
            resource_id=row["resource_id"],
            record_kind_id=row["record_kind_id"],
            claim_type=ClaimType(row["claim_type"]),
            proposition_kind=facts.get("proposition", ""),
        )
        row["reliability"] = resolve_reliability(
            scope=scope, candidates=live, supplied=row["supplied"]
        ).reliability
        by_claim.setdefault(str(row["claim_id"]), []).append(row)

    moment = datetime(2026, 9, 16, tzinfo=UTC)
    results: dict[str, Any] = {}
    for claim_id, claim_rows in sorted(by_claim.items()):
        result = aggregate(
            claim_id,
            [evidence_item_from_row(r) for r in claim_rows],
            REFERENCE_PROFILE_V1,
            temporality=ClaimTemporality(claim_rows[0]["temporality"] or "EVERGREEN"),
            claim_feature=claim_rows[0]["claim_feature"],
            now=moment,
            allow_uncalibrated=True,
        )
        results[claim_id] = json.loads(result.canonical_json())
    return {"evidence_rows": len(rows), "independence_states": states, "claims": results}


def _without(payload: dict[str, Any], fields: tuple[str, ...]) -> dict[str, Any]:
    return {k: v for k, v in payload.items() if k not in fields}


def compare_one(label: str, before: dict[str, Any], after: dict[str, Any]) -> list[str]:
    problems: list[str] = []
    ignored = ("algorithm_version", *LEVEL_FIELDS)
    if _without(before, ignored) != _without(after, ignored):
        keys = sorted(
            k
            for k in set(before) | set(after)
            if k not in ignored and before.get(k) != after.get(k)
        )
        problems.append(f"{label}: non-level fields moved: {keys}")
    if after["evidence_level"] > before["evidence_level"]:
        problems.append(
            f"{label}: level rose {before['evidence_level']} -> {after['evidence_level']}"
        )
    for field in ("reasons", "blocked_reasons"):
        moved = set(before[field]) ^ set(after[field])
        stray = [r for r in moved if not any(m in r for m in THRESHOLD_MARKERS)]
        if stray:
            problems.append(f"{label}: a non-threshold {field[:-1]} moved: {stray[0]!r}")
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--record-predecessor", action="store_true")
    mode.add_argument("--compare", action="store_true")
    args = parser.parse_args(argv)
    from sros_evidence_aggregation import ALGORITHM_VERSION

    url = os.environ.get("DATABASE_URL")
    if args.record_predecessor:
        if ALGORITHM_VERSION != PREDECESSOR_ALGORITHM:
            print(
                f"REFUSED  the predecessor is recorded under {PREDECESSOR_ALGORITHM}, not {ALGORITHM_VERSION}"
            )
            return 1
        if RECORD.exists():
            print(f"REFUSED  {RECORD.name} exists; a predecessor record is written once")
            return 1
        cases = case_results()
        record = {
            "$comment": "Mission 1.85.2 (N05). The aggregation output of every differential case and every real claim under algorithm 1.0.0, recorded before levels.py changed. Historical and immutable: never regenerate it.",
            "algorithm_version": ALGORITHM_VERSION,
            "recorded_at": datetime.now(UTC).isoformat(timespec="seconds"),
            "cases": cases,
            "case_digests": {k: _digest(v) for k, v in cases.items()},
            "real_rows": real_row_results(url) if url else None,
        }
        RECORD.write_bytes((json.dumps(record, indent=1, sort_keys=True) + "\n").encode("utf-8"))
        real = record["real_rows"]
        print(
            f"recorded {len(cases)} cases"
            + (
                f" and {len(real['claims'])} real claims over {real['evidence_rows']} rows"
                if real
                else ""
            )
        )
        return 0

    record = json.loads(RECORD.read_text("utf-8"))
    problems: list[str] = []
    after_cases = case_results()
    if set(after_cases) != set(record["cases"]):
        problems.append("the case set differs from the predecessor record")
    changed_levels = []
    for case_id, before in record["cases"].items():
        after = after_cases[case_id]
        problems += compare_one(case_id, before, after)
        if before["evidence_level"] != after["evidence_level"]:
            changed_levels.append(
                f"{case_id} {before['evidence_level']}->{after['evidence_level']}"
            )
    real_summary = "real rows not compared (no DATABASE_URL)"
    if url and record["real_rows"]:
        live = real_row_results(url)
        if live["independence_states"] != record["real_rows"]["independence_states"]:
            problems.append(f"evidence independence states moved: {live['independence_states']}")
        if set(live["claims"]) != set(record["real_rows"]["claims"]):
            problems.append("the set of real claims differs from the predecessor record")
        identical = 0
        for claim_id, before in record["real_rows"]["claims"].items():
            after = live["claims"].get(claim_id)
            if after is None:
                continue
            problems += compare_one(f"claim {claim_id}", before, after)
            if _without(before, ("algorithm_version",)) == _without(after, ("algorithm_version",)):
                identical += 1
        real_summary = f"real claims identical apart from algorithm_version: {identical}/{len(record['real_rows']['claims'])}"
    for p in problems:
        print(f"FAIL     {p}")
    print(f"levels changed: {changed_levels}")
    print(real_summary)
    if problems:
        return 1
    print("ok       no mass, count, warning, explanation or score moved; no level rose")
    return 0


if __name__ == "__main__":
    sys.exit(main())
