"""Generate docs/data/source-signal-coverage-v1.md from the catalog.

Mission 1.7 §22. Generated for the reason every other catalog view is: the
question "do we have twenty economic sources and no entertainment sources" must
be answered from the registry, not from a table somebody updated once.

It reads the catalog JSON and needs no database (ADR-009), like
`render_review_results.py`.

WHAT IT REFUSES TO DO

No weights, no scores, no per-source reliability number. §35 and §36 both forbid
one and D-03 is the reason. A coverage cell is a yes or a blank, and the columns
that look quantitative are counts of sources rather than measures of quality --
`source count is not evidence quality` is stated in the output itself because
a table of counts invites exactly that reading.
"""

import pathlib
import sys

sys.path.insert(0, "services/acquisition/python")
from sros_acquisition.registry import SIGNAL_FAMILIES, USER_BEHAVIORS, load_catalog

catalog = load_catalog("docs/data/source-catalog-v1.json")

APPROVING = {"APPROVED", "APPROVED_WITH_CONDITIONS"}
BLOCKING = {"PROHIBITED"}

# Display order: the families Mission 1.7 §2 groups as consumer/desire-driven
# first, the traditional ones last. Deliberate -- the default reading order of a
# table is an editorial claim about what matters, and this project's stated
# philosophy is that pain is one mechanism among many rather than the primary
# one (docs/CLAUDE.md, Core principles).
FAMILY_ORDER = [
    "desire",
    "entertainment",
    "creativity",
    "curiosity",
    "competition",
    "collection",
    "personalization",
    "status",
    "social",
    "community",
    "discovery",
    "learning",
    "trend",
    "commercial",
    "developer_activity",
    "problem",
]
BEHAVIOUR_ORDER = [
    "create",
    "play",
    "compete",
    "collect",
    "customize",
    "share",
    "discuss",
    "discover",
    "learn",
    "compare",
    "predict",
    "consume",
    "track",
    "buy",
    "sell",
    "collaborate",
    "automate",
]

# The display orders are hand-written, so they can fall behind the vocabulary.
# A family missing here would silently vanish from the matrix -- a column nobody
# notices is absent is worse than a crash.
if set(FAMILY_ORDER) != SIGNAL_FAMILIES:
    raise SystemExit(f"display order lost a signal family: {SIGNAL_FAMILIES ^ set(FAMILY_ORDER)}")
if set(BEHAVIOUR_ORDER) != USER_BEHAVIORS:
    raise SystemExit(f"display order lost a behaviour: {USER_BEHAVIORS ^ set(BEHAVIOUR_ORDER)}")


def usability(state: str) -> str:
    if state in APPROVING:
        return "AVAILABLE"
    if state in BLOCKING:
        return "BLOCKED"
    if state == "RESTRICTED":
        return "BLOCKED"
    return "PENDING"


sources = sorted(catalog, key=lambda s: (usability(s.review.approval_state.value), s.source_id))

L: list[str] = []
add = L.append

add("# Source signal coverage V1")
add("")
add("**Status:** Generated. Do not edit by hand.")
add("**Generated by:** `python infrastructure/scripts/render_signal_coverage.py`")
add(
    f"**Catalog version:** {catalog.catalog_version} · reviewed {catalog.review_date} "
    f"by `{catalog.reviewer}`"
)
add(
    "**Governed by:** [`source-registry-v1.md`](source-registry-v1.md), "
    "[ADR-017](../architecture/adr/ADR-017-source-signal-coverage.md)"
)
add("**Model:** [`source-coverage-gap-analysis-v1.md`](source-coverage-gap-analysis-v1.md)")
add("")
add("---")
add("")
add("## 0. What this document is, and what it is not")
add("")
add("It answers one question per source: **what kinds of opportunity signal could this**")
add("**source expose, if we were permitted to collect from it.**")
add("")
add("Three things it is not, each of which it would be easy to mistake it for:")
add("")
add("- **Not permission.** A source can cover `entertainment` and be `PROHIBITED`.")
add("  Coverage and eligibility are different tables and no view joins them into one")
add("  verdict. The usability column here is a reminder, never an input.")
add("- **Not evidence weight.** There is no number anywhere in this document. A")
add("  per-source reliability coefficient is D-03, which is blocked, and §35 names the")
add("  exact shape of the mistake: `Reddit = 0.7`.")
add("- **Not a measure of quality.** The counts below count SOURCES. Ten sources")
add("  covering a family is not better evidence than one; it is more places to look.")
add("")
add("## 1. The vocabulary")
add("")
add("Sixteen signal families and seventeen behaviours. The behaviours are Ontology V2")
add("§3.4 unchanged — Mission 1.7 §5 asked for exactly the canonical list, so no second")
add("behaviour vocabulary was created. Eleven of the sixteen signal families project a")
add("canonical `user_motivation` entry and record which one; five record no projection,")
add("four because none exists and `desire` because its counterpart is a closed enum that")
add("a registry pointer cannot reference.")
add("")

# ---------------------------------------------------------------- the matrix
add("## 2. Signal coverage matrix")
add("")
add("`•` means the source's reviewed capabilities could expose that family. Each cell")
add("is backed by a recorded `basis` naming the capability it rests on; the bases are in")
add("[`source-catalog-v1.json`](source-catalog-v1.json).")
add("")
header = "| Source | Family | Use |" + "".join(f" {f[:4]} |" for f in FAMILY_ORDER)
add(header)
add("|---|---|---|" + "---|" * len(FAMILY_ORDER))
for s in sources:
    covered = {c.signal_family for c in s.signal_coverage}
    cells = "".join(" • |" if f in covered else "  |" for f in FAMILY_ORDER)
    add(
        f"| `{s.source_id}` | {s.source_family} | {usability(s.review.approval_state.value)} |{cells}"
    )
add("")
add("Column keys, in order: " + ", ".join(f"`{f[:4]}`={f}" for f in FAMILY_ORDER) + ".")
add("")

# ------------------------------------------------------------ behaviour view
add("## 3. Behaviour coverage matrix")
add("")
add("Which canonical user behaviours (Ontology V2 §3.4) a source records evidence of.")
add("")
add("| Source | Use |" + "".join(f" {b[:4]} |" for b in BEHAVIOUR_ORDER))
add("|---|---|" + "---|" * len(BEHAVIOUR_ORDER))
for s in sources:
    covered = {c.behavior for c in s.behavior_coverage}
    if not covered:
        continue
    cells = "".join(" • |" if b in covered else "  |" for b in BEHAVIOUR_ORDER)
    add(f"| `{s.source_id}` | {usability(s.review.approval_state.value)} |{cells}")
add("")
add("Column keys, in order: " + ", ".join(f"`{b[:4]}`={b}" for b in BEHAVIOUR_ORDER) + ".")
add("")
noprofile = [s.source_id for s in catalog if not s.behavior_coverage]
add(
    f"**{len(noprofile)} sources record no behaviour at all**: "
    + ", ".join(f"`{s}`" for s in noprofile)
    + "."
)
add("")
add("Two different reasons, and they are worth separating. The economic sources record")
add("none because aggregate national statistics contain no individual behaviour — that")
add("is a property of the data and not a gap in the review. The rest record none because")
add("their documentation could not be retrieved or the source is `PROHIBITED`, so there")
add("is no basis to cite and nothing may be claimed.")
add("")

# ------------------------------------------------------------------- the gaps
add("## 4. Coverage by family, counting only what may be used")
add("")
add("§23: a `PROHIBITED` source is not coverage, and neither is a `RESTRICTED` one for")
add("this use case. **AVAILABLE** counts sources in an approving state. The other two")
add("columns are what a change of verdict would buy.")
add("")
add("| Signal family | AVAILABLE | PENDING | BLOCKED | Status |")
add("|---|---|---|---|---|")
gap_rows = []
for family in FAMILY_ORDER:
    avail, pend, blocked = [], [], []
    for s in catalog:
        if family not in {c.signal_family for c in s.signal_coverage}:
            continue
        state = s.review.approval_state.value
        (
            avail if state in APPROVING else blocked if usability(state) == "BLOCKED" else pend
        ).append(s.source_id)
    status = "**covered**" if len(avail) >= 2 else "partial" if len(avail) == 1 else "**UNCOVERED**"
    gap_rows.append((family, avail, pend, blocked, status))
    add(f"| `{family}` | {len(avail)} | {len(pend)} | {len(blocked)} | {status} |")
add("")
uncovered = [r[0] for r in gap_rows if not r[1]]
partial = [r[0] for r in gap_rows if len(r[1]) == 1]
add(
    f"**{len(uncovered)} of {len(FAMILY_ORDER)} families have no usable source at all**: "
    + ", ".join(f"`{f}`" for f in uncovered)
    + "."
)
add("")
add(
    f"**{len(partial)} rest on a single source**: "
    + ", ".join(f"`{f}`" for f in partial)
    + ". A family covered by one source is a family covered by one source's biases."
)
add("")
add("### What each uncovered family would need")
add("")
add("| Family | Would be covered by | Blocked on |")
add("|---|---|---|")
for family, avail, pend, blocked, _ in gap_rows:
    if avail:
        continue
    candidates = ", ".join(f"`{s}`" for s in (pend + blocked)) or "**nothing in the catalog**"
    reason = (
        "no registered source exposes it" if not (pend + blocked) else "verdicts, not capability"
    )
    add(f"| `{family}` | {candidates} | {reason} |")
add("")

# ------------------------------------------------------------------- balance
add("## 5. Portfolio balance")
add("")
add("§40 asks what proportion of source categories are economic rather than")
add("consumer or social. Category counts, not quality claims.")
add("")
families: dict[str, list[str]] = {}
for s in catalog:
    families.setdefault(s.source_family, []).append(s.source_id)
add("| Source family | Registered | Approving | Sources |")
add("|---|---|---|---|")
for name in sorted(families, key=lambda f: (-len(families[f]), f)):
    ids = families[name]
    approving = [
        i
        for i in ids
        if next(s for s in catalog if s.source_id == i).review.approval_state.value in APPROVING
    ]
    add(f"| `{name}` | {len(ids)} | {len(approving)} | " + ", ".join(f"`{i}`" for i in ids) + " |")
add("")
total = len(list(catalog))
economic = len(families.get("economic_data", []))
approving_all = [s for s in catalog if s.review.approval_state.value in APPROVING]
econ_approving = [s for s in approving_all if s.source_family == "economic_data"]
add(
    f"**Registered: {economic} of {total} sources are economic data "
    f"({economic * 100 // total}%), across {len(families)} families.**"
)
add(
    f"**In an approving state: {len(econ_approving)} of {len(approving_all)} "
    f"({len(econ_approving) * 100 // len(approving_all)}%).**"
)
add("")
add("The registered figure is the healthier of the two and it is the less meaningful")
add("one. What the system may actually collect from is the second, and there the")
add("economic share is far higher than the catalog as a whole suggests — which is the")
add("bias §40 asks to be reported rather than the one it hopes for.")
add("")

out = pathlib.Path("docs/data/source-signal-coverage-v1.md")
text = "\n".join(L).rstrip("\n") + "\n"
if "--check" in sys.argv:
    if not out.exists() or out.read_text(encoding="utf-8") != text:
        print(f"stale    {out} does not match the catalog. Regenerate.", file=sys.stderr)
        raise SystemExit(1)
    print(f"ok       {out} matches the catalog")
else:
    out.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote    {out}")
